# Generated by Django 3.1.1 on 2020-09-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nulo', max_length=250)),
                ('año', models.DateField()),
                ('autor', models.CharField(default='No hay autor', max_length=250)),
                ('editorial', models.CharField(default='No hay editorial', max_length=250)),
            ],
        ),
    ]
